import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./nav/NavBar";
import ToasterProvider from "./providers/ToasterProvider";
import SignalRProviderWrapper from "./providers/SignalRProviderWrapper";
import { SessionProvider } from "next-auth/react";


export const metadata: Metadata = {
  title: "Catsties App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SessionProvider>
          <ToasterProvider />
          <NavBar />
          <main className="container mx-auto px-5 pt-10">
            <SignalRProviderWrapper>
              {children}
            </SignalRProviderWrapper>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
